name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install bash bats git
          git --version
          bats --version
      - name: Run BATS test suite
        run: |
          ./test.bats
